<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kategori_rfo extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        //is_login();
        $this->load->model('Kategori_rfo_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','kategori_rfo/tbl_kategori_rfo_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Kategori_rfo_model->json();
    }

    public function read($id) 
    {
        $row = $this->Kategori_rfo_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_kategori_rfo' => $row->id_kategori_rfo,
		'nama_kategori_rfo' => $row->nama_kategori_rfo,
	    );
            $this->template->load('template','kategori_rfo/tbl_kategori_rfo_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kategori_rfo'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('kategori_rfo/create_action'),
	    'id_kategori_rfo' => set_value('id_kategori_rfo'),
	    'nama_kategori_rfo' => set_value('nama_kategori_rfo'),
	);
        $this->template->load('template','kategori_rfo/tbl_kategori_rfo_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_kategori_rfo' => $this->input->post('nama_kategori_rfo',TRUE),
	    );

            $this->Kategori_rfo_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('kategori_rfo'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Kategori_rfo_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('kategori_rfo/update_action'),
		'id_kategori_rfo' => set_value('id_kategori_rfo', $row->id_kategori_rfo),
		'nama_kategori_rfo' => set_value('nama_kategori_rfo', $row->nama_kategori_rfo),
	    );
            $this->template->load('template','kategori_rfo/tbl_kategori_rfo_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kategori_rfo'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_kategori_rfo', TRUE));
        } else {
            $data = array(
		'nama_kategori_rfo' => $this->input->post('nama_kategori_rfo',TRUE),
	    );

            $this->Kategori_rfo_model->update($this->input->post('id_kategori_rfo', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('kategori_rfo'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Kategori_rfo_model->get_by_id($id);

        if ($row) {
            $this->Kategori_rfo_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('kategori_rfo'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kategori_rfo'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_kategori_rfo', 'nama kategori rfo', 'trim|required');

	$this->form_validation->set_rules('id_kategori_rfo', 'id_kategori_rfo', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Kategori_rfo.php */
/* Location: ./application/controllers/Kategori_rfo.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-12-18 00:37:29 */
/* http://harviacode.com */