<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_tes extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Tbl_tes_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','tbl_tes/tbl_tes_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Tbl_tes_model->json();
    }

    public function read($id) 
    {
        $row = $this->Tbl_tes_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_tes' => $row->id_tes,
		'tanggal_jam' => $row->tanggal_jam,
		'waktu_selesai' => $row->waktu_selesai,
	    );
            $this->template->load('template','tbl_tes/tbl_tes_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tbl_tes'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('tbl_tes/create_action'),
	    'id_tes' => set_value('id_tes'),
	    'tanggal_jam' => set_value('tanggal_jam'),
	    'waktu_selesai' => set_value('waktu_selesai'),
	);
        $this->template->load('template','tbl_tes/tbl_tes_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'tanggal_jam' => $this->input->post('tanggal_jam',TRUE),
		'waktu_selesai' => $this->input->post('waktu_selesai',TRUE),
	    );

            $this->Tbl_tes_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('tbl_tes'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tbl_tes_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('tbl_tes/update_action'),
		'id_tes' => set_value('id_tes', $row->id_tes),
		'tanggal_jam' => set_value('tanggal_jam', $row->tanggal_jam),
		'waktu_selesai' => set_value('waktu_selesai', $row->waktu_selesai),
	    );
            $this->template->load('template','tbl_tes/tbl_tes_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tbl_tes'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_tes', TRUE));
        } else {
            $data = array(
		'tanggal_jam' => $this->input->post('tanggal_jam',TRUE),
		'waktu_selesai' => $this->input->post('waktu_selesai',TRUE),
	    );

            $this->Tbl_tes_model->update($this->input->post('id_tes', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('tbl_tes'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tbl_tes_model->get_by_id($id);

        if ($row) {
            $this->Tbl_tes_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('tbl_tes'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tbl_tes'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('tanggal_jam', 'tanggal jam', 'trim|required');
	$this->form_validation->set_rules('waktu_selesai', 'waktu selesai', 'trim|required');

	$this->form_validation->set_rules('id_tes', 'id_tes', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Tbl_tes.php */
/* Location: ./application/controllers/Tbl_tes.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-12-15 22:21:29 */
/* http://harviacode.com */