<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Maintenance_harian_model extends CI_Model
{

    public $table   = 'maintenance_harian';
    public $id      = 'id_maintenance_harian';
    public $order   = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_maintenance_harian,label_odp,foto_odp,foto_redaman_sebelum,taging_odp,nama_kendala,in_sc_nama,nama_req,nama_zone,datetime_lapor,date_lapor');
        $this->datatables->from('maintenance_harian');
        //add this line for join
        $this->datatables->join('tbl_kendala', 'maintenance_harian.id_kendala = tbl_kendala.id_kendala');
        $this->datatables->join('tbl_req', 'maintenance_harian.id_req = tbl_req.id_req');
        $this->datatables->join('tbl_zone', 'maintenance_harian.id_zone = tbl_zone.id_zone');
        $this->datatables->add_column('action', anchor(site_url('maintenance_harian/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-sm'))." 

            ".anchor(site_url('maintenance_harian/proses_gangguan/$1'),'<i class="fa fa-gears" aria-hidden="true"></i>', array('class' => 'btn btn-success btn-sm'))."

            ".anchor(site_url('maintenance_harian/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-sm'))." 

            ".anchor(site_url('maintenance_harian/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Apakah Anda Yakin ?\')"'), 'id_maintenance_harian');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    
    function get_by_ids($id)
    {
        $this->db->select('id_maintenance_harian,label_odp,foto_odp,foto_redaman_sebelum,taging_odp,nama_kendala,in_sc_nama,nama_req,nama_zone,datetime_lapor,date_lapor, nama_sto');
        //$this->db->from('prov');
        $this->db->join('tbl_kendala', 'maintenance_harian.id_kendala = tbl_kendala.id_kendala');
        $this->db->join('tbl_req', 'maintenance_harian.id_req= tbl_req.id_req');
        $this->db->join('tbl_zone', 'maintenance_harian.id_zone = tbl_zone.id_zone');
        $this->db->join('tbl_sto', 'maintenance_harian.id_sto = tbl_sto.id_sto');
        $this->db->where($this->id, $id);

        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_maintenance_harian', $q);
        $this->db->like('id_sto', $q);
    	$this->db->or_like('label_odp', $q);
    	$this->db->or_like('foto_odp', $q);
    	$this->db->or_like('foto_redaman_sebelum', $q);
    	$this->db->or_like('taging_odp', $q);
    	$this->db->or_like('id_kendala', $q);
    	$this->db->or_like('in_sc_nama', $q);
    	$this->db->or_like('id_req', $q);
    	$this->db->or_like('id_zone', $q);
    	$this->db->or_like('datetime_lapor', $q);
    	$this->db->or_like('date_lapor', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_maintenance_harian', $q);
        $this->db->like('id_sto', $q);
    	$this->db->or_like('label_odp', $q);
    	$this->db->or_like('foto_odp', $q);
    	$this->db->or_like('foto_redaman_sebelum', $q);
    	$this->db->or_like('taging_odp', $q);
    	$this->db->or_like('id_kendala', $q);
    	$this->db->or_like('in_sc_nama', $q);
    	$this->db->or_like('id_req', $q);
    	$this->db->or_like('id_zone', $q);
    	$this->db->or_like('datetime_lapor', $q);
    	$this->db->or_like('date_lapor', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Maintenance_harian_model.php */
/* Location: ./application/models/Maintenance_harian_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-12-11 00:13:58 */
/* http://harviacode.com */