<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Process_maintenance_harian_model extends CI_Model
{

    public $table = 'process_maintenance_harian';
    public $id = 'id_process_maintenance_harian';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_process_maintenance_harian,foto_redaman_sesudah, foto_redaman_sesudah ,rfo,material,datetime_selesai, label_odp, datetime_lapor,     in_sc_nama, foto_odp, nama_status ');
        $this->datatables->from('process_maintenance_harian');
        //add this line for join
        $this->datatables->join('maintenance_harian', 'process_maintenance_harian.id_maintenance_harian = maintenance_harian.id_maintenance_harian');
        //$this->datatables->join('tbl_team', 'process_maintenance_harian.id_team = tbl_team.id_team');
        $this->datatables->join('tbl_status', 'process_maintenance_harian.id_status = tbl_status.id_status');
        $this->datatables->add_column('action', anchor(site_url('process_maintenance_harian/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('process_maintenance_harian/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('process_maintenance_harian/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_process_maintenance_harian');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_ids($id)
    {
        $this->db->select('id_process_maintenance_harian,label_odp,foto_redaman_sesudah,rfo,material,nama_team,nama_status,nama_kategori_rfo_detail,nama_kategori_rfo');
        //$this->db->from('prov');
        $this->db->join('maintenance_harian', 'process_maintenance_harian.id_maintenance_harian = maintenance_harian.id_maintenance_harian');
        $this->db->join('tbl_team', 'process_maintenance_harian.id_team= tbl_team.id_team');
        $this->db->join('tbl_status', 'process_maintenance_harian.id_status = tbl_status.id_status');
        $this->db->join('tbl_kategori_rfo', 'process_maintenance_harian.id_kategori_rfo = tbl_kategori_rfo.id_kategori_rfo');
        $this->db->join('tbl_kategori_rfo_detail', 'process_maintenance_harian.id_tbl_kategori_rfo_detail = tbl_kategori_rfo_detail.id_tbl_kategori_rfo_detail');
        $this->db->where($this->id, $id);

        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_process_maintenance_harian', $q);
	$this->db->or_like('id_maintenance_harian', $q);
	$this->db->or_like('foto_redaman_sesudah', $q);
	$this->db->or_like('id_team', $q);
	$this->db->or_like('rfo', $q);
	$this->db->or_like('material', $q);
	$this->db->or_like('datetime_selesai', $q);
	$this->db->or_like('id_status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_process_maintenance_harian', $q);
	$this->db->or_like('id_maintenance_harian', $q);
	$this->db->or_like('foto_redaman_sesudah', $q);
	$this->db->or_like('id_team', $q);
	$this->db->or_like('rfo', $q);
	$this->db->or_like('material', $q);
	$this->db->or_like('datetime_selesai', $q);
	$this->db->or_like('id_status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Process_maintenance_harian_model.php */
/* Location: ./application/models/Process_maintenance_harian_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-12-03 23:38:08 */
/* http://harviacode.com */