<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class View_maintenance_harian_model extends CI_Model
{

    public $table = 'view_maintenance_harian';
    public $id = 'id_maintenance_harian';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_maintenance_harian,label_odp,foto_odp,foto_redaman_sebelum,taging_odp,in_sc_nama,datetime_lapor,foto_redaman_sesudah,rfo,material,datetime_selesai,durasi,nama_kendala,nama_req,nama_zone,nama_team,nama_status,nama_kategori_rfo_detail,nama_kategori_rfo');
        $this->datatables->from('view_maintenance_harian');
        //add this line for join
        //$this->datatables->join('maintenance_harian', 'process_maintenance_harian.id_maintenance_harian = maintenance_harian.id_maintenance_harian');
        //$this->datatables->join('tbl_team', 'process_maintenance_harian.id_team = tbl_team.id_team');
        //$this->datatables->join('tbl_status', 'process_maintenance_harian.id_status = tbl_status.id_status');
        $this->datatables->add_column('action', anchor(site_url('view_maintenance_harian/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm')), 'id_maintenance_harian');

        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_process_maintenance_harian', $q);
	$this->db->or_like('id_maintenance_harian', $q);
	$this->db->or_like('foto_redaman_sesudah', $q);
	$this->db->or_like('nama_team', $q);
	$this->db->or_like('rfo', $q);
	$this->db->or_like('material', $q);
	$this->db->or_like('datetime_selesai', $q);
	$this->db->or_like('id_status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_process_maintenance_harian', $q);
	$this->db->or_like('id_maintenance_harian', $q);
	$this->db->or_like('foto_redaman_sesudah', $q);
	$this->db->or_like('id_team', $q);
	$this->db->or_like('rfo', $q);
	$this->db->or_like('material', $q);
	$this->db->or_like('datetime_selesai', $q);
	$this->db->or_like('id_status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Process_maintenance_harian_model.php */
/* Location: ./application/models/Process_maintenance_harian_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-12-03 23:38:08 */
/* http://harviacode.com */